spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_03
    username: myusername
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Można zmienić na "create" w trybie deweloperskim, aby tworzyć tabele przy każdym uruchomieniu
    show-sql: false # Włącz wyświetlanie zapytań SQL w konsoli na potrzeby trybu deweloperskiego (false/true)
  database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Ustawienia dla obsługi przesyłania plików
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

