spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/baza_erp
    username: myusername
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Mo?esz zmieni? na "create" w trybie deweloperskim, aby tworzy? tabele przy ka?dym uruchomieniu
    show-sql: true # W??cz wy?wietlanie zapyta? SQL w konsoli (dobrze w trybie deweloperskim)
  database-platform: org.hibernate.dialect.PostgreSQLDialect

